[project]
name = "racegame"
version = "0.1.0"
description = "Emerson's racing game"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.116.1",
    "isort>=6.0.1",
    "pytest>=8.4.2",
    "python-fasthtml>=0.12.27",
]
